spring.application.name=staj-takip

# Gmail SMTP server host
spring.mail.host=smtp.gmail.com

# Standard port for TLS (recommended)
spring.mail.port=587

# Your full Gmail email address
spring.mail.username=${MAIL_USERNAME}

# Your generated App Password (not your regular Gmail password)
spring.mail.password=${MAIL_PASSWORD}

# Enable SMTP authentication
spring.mail.properties.mail.smtp.auth=true

# Enable STARTTLS for secure connection
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: You can also set this to true
# spring.mail.properties.mail.smtp.starttls.required=true
springdoc.override-with-generic-response=false

